/*
 * Copyright (C) 2004-2026 ZNC, see the NOTICE file for details.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <znc/FileConfigProvider.h>
#include <znc/Config.h>
#include <cerrno>
#include <cstring>

FileConfigProvider::FileConfigProvider(const CString& sFilePath)
    : m_sFilePath(sFilePath) {}

bool FileConfigProvider::Load(CConfig& config, CString& sError) {
    sError.clear();

    if (!CFile::Exists(m_sFilePath)) {
        sError = "No such file";
        return false;
    }

    if (!CFile::IsReg(m_sFilePath)) {
        sError = "Not a file";
        return false;
    }

    auto pFile = std::make_unique<CFile>(m_sFilePath);

    // Open Read/Write so that fcntl() exclusive locking works correctly.
    if (!pFile->Open(m_sFilePath, O_RDWR)) {
        sError = "Can not open config file";
        return false;
    }

    if (!pFile->TryExLock()) {
        sError = "ZNC is already running on this config.";
        return false;
    }

    // Transfer ownership of the lock file so the lock is held for the
    // lifetime of this provider.
    m_pLockFile = std::move(pFile);

    if (!config.Parse(*m_pLockFile, sError)) {
        return false;
    }

    return true;
}

bool FileConfigProvider::Save(const CConfig& config, CString& sError) {
    sError.clear();

    if (m_sFilePath.empty()) {
        sError = "Config file path is empty";
        return false;
    }

    // Write to a temporary file first; then atomically replace the real one.
    auto pTmp = std::make_unique<CFile>(m_sFilePath + "~");

    if (!pTmp->Open(O_WRONLY | O_CREAT | O_TRUNC, 0600)) {
        sError = "Could not open temp config file for writing: " +
                 CString(strerror(errno));
        return false;
    }

    // Acquire an exclusive lock on the temporary file so we "transfer" our
    // existing lock from the old inode to the new one.
    if (!pTmp->TryExLock()) {
        sError = "Error while locking the new config file: " +
                 CString(strerror(errno));
        pTmp->Delete();
        return false;
    }

    // Write header comment.
    pTmp->Write("// WARNING\n"
                "//\n"
                "// Do NOT edit this file while ZNC is running!\n"
                "// Use webadmin or *controlpanel instead.\n"
                "//\n"
                "// Altering this file by hand will forfeit all support.\n"
                "//\n"
                "// But if you feel risky, you might want to read help on"
                " /znc saveconfig and /znc rehash.\n"
                "// Also check https://wiki.znc.in/Configuration\n\n");

    const_cast<CConfig&>(config).Write(*pTmp);

    pTmp->Sync();

    if (pTmp->HadError()) {
        sError = "Write error: " + CString(strerror(errno));
        pTmp->Delete();
        return false;
    }

    if (!pTmp->Move(m_sFilePath, true)) {
        sError = "Could not replace config file: " + CString(strerror(errno));
        pTmp->Delete();
        return false;
    }

    pTmp->SetFileName(m_sFilePath);
    m_pLockFile = std::move(pTmp);

    return true;
}
